name: Flake8 and PyTest

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

env:
  APP_ENV: test
  SQL_ALCHEMY_DATABASE_URL: sqlite:///db.sqlite
  JWT_SECRET_KEY: supersecretkey
  JWT_ALGORITHM: HS256
  JWT_EXPIRES_IN: 20
jobs:
  flake8_and_pytest:
    name: Flake and Pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv poetry
        virtualenv venv
        source venv/bin/activate
        poetry export --without-hashes --format=requirements.txt > requirements.txt
        pip install -r requirements.txt
    
    - name: Run flake8
      run: |
        source venv/bin/activate
        env
        flake8 --max-line-length 88 --ignore F403,F401 app/
          
    - name: Run pytest
      run: |
        source venv/bin/activate
        env
        coverage run -m pytest --cov app/api --cov-report term --cov-report xml:coverage.xml --cov-fail-under 85